<img id="imgpagantisfront" src="<?php echo $this->getSkinUrl('images/pagantis/logopagamastarde.png') ?>"/>
<?php $_code = $this->getMethodCode() ?>
<a href='http://www.pagantis.com' target="_blank"
   title='<?php echo $this->__('La nueva generación de pagos online. 1ª Entidad de Pago española nativa digital autorizada por el Ministerio de Economía y Competitividad.'); ?>'>
    <?php echo $this->__(
        'Más información'
    ) ?></a>